

############################################################
# newConnHandler
############################################################

#' @title newConnHandler
#' @description Create a handler to connect to a remote database.
#' @param dbname Name of MySQL database (required)
#' @param host Name of the server where MySQL database is hosted on (required)
#' @param port Port on the server to connect to MySQL database (required)
#' @param user Name of user to establish the connection (required)
#' @param password Password associated with the user (required)
#' @param api_host Name of the server where the API is hosted on (required)
#' @param api_port Port on the server to access the API (required)
#' @return A list object containing connection parameters.
#' @export

newConnHandler <- function(
    dbname = "sigrepo",
    host = "sigrepo.org",
    port = 3306,
    user = "guest",
    password = "guest",
    api_host = "http://142.93.67.157:8020",
    api_port = 8020
){
  
  valid_port <- function(x) {
    is.numeric(x) &&
      length(x) == 1 &&
      !is.na(x) &&
      is.finite(x) &&
      x == as.integer(x) &&
      x >= 1 &&
      x <= 65535
  }
  
  # Input checks
  stopifnot(
    "'dbname' must have length 1 and not be empty." =
      (length(dbname) == 1 && !dbname %in% c(NA, "")),
    "'host' must have length 1 and not be empty." =
      (length(host) == 1 && !host %in% c(NA, "")),
    "'port' must be an integer in [1, 65535]." = valid_port(port),
    "'user' must have length 1 and not be empty." =
      (length(user) == 1 && !user %in% c(NA, "")),
    "'password' must have length 1 and not be empty." =
      (length(password) == 1 && !password %in% c(NA, "")),
    "'api_host' must have length 1 and not be empty." =
      (length(api_host) == 1 && !api_host %in% c(NA, "")),
    "'api_port' must be an integer in [1, 65535]." = valid_port(api_port)
  )
  
  handle <- list(
    dbname = dbname,
    host = host,
    port = as.numeric(port),
    user = user,
    password = password,
    api_host = api_host,
    api_port = as.numeric(api_port)
  )
  
  # store internally
  
  .sigrepo_env$handle <- handle
  
  return(invisible(handle))
}


############################################################
# Handle Management
############################################################

#' @title init_handle
#' @description Store a connection handler in package-private state.
#' @param handle A list object generated by [newConnHandler()].
#' @return Invisibly returns the stored handle.
#' @export
init_handle <- function(handle){
  
  if (is.null(handle))
    stop("Cannot initialize handle with NULL.")
  
  .sigrepo_env$handle <- handle
  
  invisible(.sigrepo_env$handle)
}


#' @title get_handle
#' @description Get the active connection handler from package-private state.
#' @return A list object generated by [newConnHandler()].
#' @export
get_handle <- function(){
  
  if (is.null(.sigrepo_env$handle))
    stop("No active handle for the database connection found.")
  
  return(.sigrepo_env$handle)
}


#' @title clear_handle
#' @description Clear the active connection handler from package-private state.
#' @return Invisibly returns `TRUE`.
#' @export
clear_handle <- function(){
  
  if (is.null(.sigrepo_env$handle))
    stop("No active handle to clear.")
  
  .sigrepo_env$handle <- NULL
  
  invisible(TRUE)
}


#' @title get_api_handle
#' @description Resolve the connection handler for API calls.
#' @param conn_handler Optional handler from [newConnHandler()].
#' If NULL, the stored internal handle is used.
#' @return A list object generated by [newConnHandler()].
#' @keywords internal
#' @export
get_api_handle <- function(conn_handler = NULL){

  if (!is.null(conn_handler)) {
    return(conn_handler)
  }

  get_handle()
}


#' @title build_api_url
#' @description Build an API URL from a resolved connection handler.
#' @param conn_handler Optional handler from [newConnHandler()].
#' If NULL, the stored internal handle is used.
#' @param endpoint API endpoint path without a leading slash.
#' @param query Named list of query string values.
#' @return A length-1 character URL.
#' @keywords internal
#' @export
build_api_url <- function(
    conn_handler = NULL,
    endpoint,
    query = list()
){

  api_handle <- get_api_handle(conn_handler)

  if (length(endpoint) != 1 || endpoint %in% c(NA, "")) {
    stop("'endpoint' must have length 1 and not be empty.")
  }

  base_url <- api_handle$api_host[1]

  if (!grepl("^https?://", base_url, perl = TRUE)) {
    base_url <- paste0("http://", base_url)
  }

  base_url <- sub("/+$", "", base_url)

  if (!grepl(":[0-9]+$", base_url, perl = TRUE)) {
    base_url <- sprintf("%s:%s", base_url, api_handle$api_port[1])
  }

  query_string <- ""
  if (length(query) > 0) {
    query_string <- paste0(
      "?",
      paste0(
        utils::URLencode(names(query), reserved = TRUE),
        "=",
        vapply(query, utils::URLencode, character(1), reserved = TRUE),
        collapse = "&"
      )
    )
  }

  sprintf("%s/%s%s", base_url, sub("^/+", "", endpoint), query_string)
}


#' @title stop_for_api_error
#' @description Raise a more informative API error from an httr response.
#' @param res httr response object.
#' @param api_url Request URL.
#' @param action Human-readable action description.
#' @keywords internal
#' @export
stop_for_api_error <- function(
    res,
    api_url,
    action
){

  response_text <- base::tryCatch(
    httr::content(res, as = "text", encoding = "UTF-8"),
    error = function(e) ""
  )

  response_text <- base::trimws(response_text)
  if (base::nchar(response_text) > 300) {
    response_text <- base::paste0(base::substr(response_text, 1, 300), "...")
  }

  base::stop(
    base::sprintf(
      "\nAPI request failed while trying to %s.\nStatus code: %s\nURL: %s\n",
      action,
      res$status_code,
      api_url
    ),
    if (base::nchar(response_text) > 0) {
      base::sprintf("Response body: %s\n", response_text)
    } else {
      ""
    },
    "Please check your API host/port and whether the SigRepo API is running.\n"
  )
}


############################################################
# conn_init
############################################################

#' @title conn_close
#' @description Close a connection opened by conn_init(). Meant for
#' on.exit() right after conn_init(), so error paths don't leak connections.
#' Many functions also disconnect by hand before returning or stopping, and
#' RMySQL errors on a second dbDisconnect(), so that error is swallowed here.
#' @param conn A MySQL connection object from conn_init().
#' @noRd
conn_close <- function(conn){
  base::invisible(base::tryCatch(
    base::suppressWarnings(DBI::dbDisconnect(conn)),
    error = function(e) FALSE
  ))
}

#' @title conn_init
#' @description Initiate a remote database connection
#' @param conn_handler Optional handler from newConnHandler().
#' If NULL, will use stored internal handle.
#' @return A MySQL connection object.
#' @export
#' @import DBI RMySQL

conn_init <- function(conn_handler = NULL){
  
  if (!is.null(conn_handler)) {
    # Optional: update stored handle
    init_handle(conn_handler)
  } else {
    conn_handler <- get_handle()
  }
  
  if (is.null(conn_handler)) {
    stop("No active handle for the database connection found.")
  }
  
  dbname <- conn_handler$dbname
  host <- conn_handler$host
  port <- conn_handler$port
  user <- conn_handler$user
  password <- conn_handler$password
  
  conn <- tryCatch({
    DBI::dbConnect(
      drv = RMySQL::MySQL(),
      dbname = dbname,
      host = host,
      port = port,
      user = user,
      password = password
    )
  }, error = function(e){
    stop(
      "Failed to connect to the database.\n",
      "Please check your host, username, password, and network connection.\n",
      "Technical details: ", as.character(e)
    )
  })
  
  ##########################################################
  # Root Auto-Provision Logic
  ##########################################################
  
  if (user == "root") {
    
    user_tbl <- SigRepo::lookup_table_sql(
      conn = conn,
      db_table_name = "users",
      return_var = "user_name",
      filter_coln_var = "user_name",
      filter_coln_val = list("user_name" = user),
      check_db_table = TRUE
    )
    
    if (nrow(user_tbl) == 0) {
      
      table <- data.frame(
        user_name = user,
        user_password = password,
        user_email = "root@bu.edu",
        user_first = "root",
        user_last = "root",
        user_affiliation = "Boston University",
        user_role = "admin",
        active = 1,
        stringsAsFactors = FALSE
      )
      
      table <- SigRepo::createHashKey(
        table = table,
        hash_var = "user_password_hashkey",
        hash_columns = "user_password",
        hash_method = "md5"
      )
      
      table <- SigRepo::createHashKey(
        table = table,
        hash_var = "api_key",
        hash_columns = c("user_name", "user_email", "user_role"),
        hash_method = "md5"
      )
      
      table <- SigRepo::createHashKey(
        table = table,
        hash_var = "user_hashkey",
        hash_columns = "user_name",
        hash_method = "md5"
      )
      
      table <- SigRepo::removeDuplicates(
        conn = conn,
        db_table_name = "users",
        table = table,
        coln_var = "user_hashkey",
        check_db_table = FALSE
      )
      
      SigRepo::insert_table_sql(
        conn = conn,
        db_table_name = "users",
        table = table,
        check_db_table = FALSE
      )
    }
  }
  
  return(conn)
}
